// Code generated by MockGen. DO NOT EDIT.
// Source: C:/git/metrics/internal/repository/storage.go

// Package mock is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Happy-skills/metrics/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// GetValue mocks base method.
func (m *MockStorage) GetValue(ctx context.Context, mType, mName string) (*models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValue", ctx, mType, mName)
	ret0, _ := ret[0].(*models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValue indicates an expected call of GetValue.
func (mr *MockStorageMockRecorder) GetValue(ctx, mType, mName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockStorage)(nil).GetValue), ctx, mType, mName)
}

// GetValues mocks base method.
func (m *MockStorage) GetValues(ctx context.Context) map[string]models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValues", ctx)
	ret0, _ := ret[0].(map[string]models.Metrics)
	return ret0
}

// GetValues indicates an expected call of GetValues.
func (mr *MockStorageMockRecorder) GetValues(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValues", reflect.TypeOf((*MockStorage)(nil).GetValues), ctx)
}

// GetValuesSlice mocks base method.
func (m *MockStorage) GetValuesSlice() []models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValuesSlice")
	ret0, _ := ret[0].([]models.Metrics)
	return ret0
}

// GetValuesSlice indicates an expected call of GetValuesSlice.
func (mr *MockStorageMockRecorder) GetValuesSlice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValuesSlice", reflect.TypeOf((*MockStorage)(nil).GetValuesSlice))
}

// Ping mocks base method.
func (m *MockStorage) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockStorageMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockStorage)(nil).Ping), ctx)
}

// ResetValue mocks base method.
func (m *MockStorage) ResetValue(mType, mName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetValue", mType, mName)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetValue indicates an expected call of ResetValue.
func (mr *MockStorageMockRecorder) ResetValue(mType, mName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetValue", reflect.TypeOf((*MockStorage)(nil).ResetValue), mType, mName)
}

// SetValue mocks base method.
func (m *MockStorage) SetValue(ctx context.Context, mType, mName string, mValue any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetValue", ctx, mType, mName, mValue)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetValue indicates an expected call of SetValue.
func (mr *MockStorageMockRecorder) SetValue(ctx, mType, mName, mValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetValue", reflect.TypeOf((*MockStorage)(nil).SetValue), ctx, mType, mName, mValue)
}

// SetValues mocks base method.
func (m *MockStorage) SetValues(ctx context.Context, models []models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetValues", ctx, models)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetValues indicates an expected call of SetValues.
func (mr *MockStorageMockRecorder) SetValues(ctx, models interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetValues", reflect.TypeOf((*MockStorage)(nil).SetValues), ctx, models)
}

// SetValuesFromSlice mocks base method.
func (m *MockStorage) SetValuesFromSlice(metrics []models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetValuesFromSlice", metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetValuesFromSlice indicates an expected call of SetValuesFromSlice.
func (mr *MockStorageMockRecorder) SetValuesFromSlice(metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetValuesFromSlice", reflect.TypeOf((*MockStorage)(nil).SetValuesFromSlice), metrics)
}
